//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WarehouseDBEntities : DbContext
    {
        public WarehouseDBEntities()
            : base("name=WarehouseDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<department> department { get; set; }
        public virtual DbSet<admini> admini { get; set; }
        public virtual DbSet<Bill> Bill { get; set; }
        public virtual DbSet<client> client { get; set; }
        public virtual DbSet<depot> depot { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<product> product { get; set; }
        public virtual DbSet<Purchase> Purchase { get; set; }
        public virtual DbSet<Shipping> Shipping { get; set; }
        public virtual DbSet<ShippingFrom> ShippingFrom { get; set; }
        public virtual DbSet<ShippingSnap> ShippingSnap { get; set; }
        public virtual DbSet<staff> staff { get; set; }
        public virtual DbSet<supplier> supplier { get; set; }
        public virtual DbSet<type> type { get; set; }
    }
}
