//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipping
    {
        public int ShippingId { get; set; }
        public int clientId { get; set; }
        public int number { get; set; }
        public int status { get; set; }
        public int ProductId { get; set; }
        public System.DateTime ShippingTime { get; set; }
    
        public virtual client client { get; set; }
        public virtual product product { get; set; }
    }
}
